// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOrD1JXafCQgJrXX6b0FKSYntXui7s08E',
    appId: '1:626759180262:web:465315aa459a76d613c027',
    messagingSenderId: '626759180262',
    projectId: 'fir-tutorial-d6f14',
    authDomain: 'fir-tutorial-d6f14.firebaseapp.com',
    storageBucket: 'fir-tutorial-d6f14.appspot.com',
    measurementId: 'G-F3X9CT6Q4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF73gwzgOPfn4x4QVnHbggs7-E3R4KmeM',
    appId: '1:626759180262:android:8d0093226a6c007e13c027',
    messagingSenderId: '626759180262',
    projectId: 'fir-tutorial-d6f14',
    storageBucket: 'fir-tutorial-d6f14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbMcM8w43ILdRxaGWRmflJlwXc5xxjBHk',
    appId: '1:626759180262:ios:f11bfb7cf7e8179813c027',
    messagingSenderId: '626759180262',
    projectId: 'fir-tutorial-d6f14',
    storageBucket: 'fir-tutorial-d6f14.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbMcM8w43ILdRxaGWRmflJlwXc5xxjBHk',
    appId: '1:626759180262:ios:f11bfb7cf7e8179813c027',
    messagingSenderId: '626759180262',
    projectId: 'fir-tutorial-d6f14',
    storageBucket: 'fir-tutorial-d6f14.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOrD1JXafCQgJrXX6b0FKSYntXui7s08E',
    appId: '1:626759180262:web:d5fd5633e1f9473213c027',
    messagingSenderId: '626759180262',
    projectId: 'fir-tutorial-d6f14',
    authDomain: 'fir-tutorial-d6f14.firebaseapp.com',
    storageBucket: 'fir-tutorial-d6f14.appspot.com',
    measurementId: 'G-1HS3XNC91W',
  );
}
